name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - tolmachev-pravo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Provide a description of the issue you're experiencing.
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide a description of what you expect to happen.
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context/Possible solution
      description: Add any other context about the problem here.
    validations:
      required: false
