name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - tolmachev-pravo
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request report!
        Please complete the below template to ensure we have the necessary details.
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you're interested in.
    validations:
      required: true
      
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like. A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
